services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile.relay
    ports:
      - '4433:4433/udp'
    volumes:
      - ./cert:/etc/relay/cert:ro

  room-server:
    build:
      context: ./apps/room-server
    ports:
      - '3001:3001'

  client:
    build:
      context: ./apps/client
    ports:
      - '4173:4173'
